volumes:
  database_data:
  database_admin_data:
  s3_data:
  prometheus_data:
  grafana_data:

services:
  broker:
    image: rabbitmq:3.11.11-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=${BROKER_USER}
      - RABBITMQ_DEFAULT_PASS=${BROKER_PASSWORD}
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  database:
    image: postgres:15.2-alpine
    volumes:
      - database_data:/var/lib/postgresql/data
    env_file: ./.env
    ports:
      - 5432:5432
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  database-admin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80"
    volumes:
      - database_admin_data:/var/lib/pgadmin
    depends_on:
      - database

  s3:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000" #api
      - "9001:9001" #web
    volumes:
      - s3_data:/data
    restart: unless-stopped

  chat: &chat
    build:
      context: .
      dockerfile: ./apps/chat/Dockerfile
    env_file: ./apps/chat/.env
    ports:
      - 8000:8080
    volumes:
      - ./apps/chat/app:/app/apps/chat/app
      - ./apps/chat/migrations:/app/apps/chat/migrations
    restart: unless-stopped
    depends_on:
      database:
        condition: service_started
      centrifugo:
        condition: service_started
      broker:
        condition: service_healthy

  chat-migrator:
    <<: *chat
    ports: []
    working_dir: /app/apps/chat
    command: alembic upgrade head
    restart: no

  storage: &storage
    build:
      context: .
      dockerfile: ./apps/storage/Dockerfile
    env_file: ./apps/storage/.env
    ports:
      - 8004:8080
    volumes:
      - ./apps/storage/app:/app/apps/storage/app
      - ./apps/storage/migrations:/app/apps/storage/migrations
    restart: unless-stopped
    depends_on:
      database:
        condition: service_started
      s3:
        condition: service_started

  storage-migrator:
    <<: *storage
    ports: []
    working_dir: /app/apps/storage
    command: alembic upgrade head
    restart: no

  email_connector:
    build:
      context: .
      dockerfile: ./apps/email_connector/Dockerfile
    env_file: ./apps/email_connector/.env
    ports:
      - 8003:8080
    volumes:
      - ./apps/email_connector/app:/app/apps/email_connector/app
    restart: unless-stopped
    depends_on:
      broker:
        condition: service_healthy

  telegram_connector:
    build:
      context: .
      dockerfile: ./apps/telegram_connector/Dockerfile
    env_file: ./apps/telegram_connector/.env
    ports:
      - 8002:8080
    volumes:
      - ./apps/telegram_connector/app:/app/apps/telegram_connector/app
    restart: unless-stopped
    depends_on:
      broker:
        condition: service_healthy

  centrifugo:
    image: centrifugo/centrifugo:v6
    volumes:
      - ./configs/centrifugo/config.json:/centrifugo/config.json
    restart: unless-stopped
    command: centrifugo -c /centrifugo/config.json
    ports:
      - 8001:8000
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./configs/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=100h"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./configs/monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./configs/monitoring/grafana/dashboards:/etc/grafana/dashboards
    depends_on:
      - prometheus

  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:latest
    command: -config.file=/etc/promtail/promtail.yml
    volumes:
      - ./configs/monitoring/promtail.yml:/etc/promtail/promtail.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - loki
