global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "metrics"
    static_configs:
      - targets: ["chat:8080"]
        labels:
          service: chat
      - targets: ["storage:8080"]
        labels:
          service: storage
      - targets: ["telegram_connector:8080"]
        labels:
          service: telegram_connector
      - targets: ["email_connector:8080"]
        labels:
          service: email_connector

    metrics_path: /metrics
