"""added last_read table

Revision ID: 1c38e17ccaa9
Revises: e81e8ccace90
Create Date: 2026-05-06 17:22:58.268054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c38e17ccaa9'
down_revision: Union[str, Sequence[str], None] = 'e81e8ccace90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('last_reads',
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('last_reads_conversation_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('last_reads_message_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], name=op.f('last_reads_operator_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('last_reads_pkey')),
    sa.UniqueConstraint('conversation_id', 'operator_id', name='conversation_operator_idx')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('last_reads')
    # ### end Alembic commands ###
