"""alter messages table added delivery_status column

Revision ID: 2098aad53180
Revises: d74cc7071334
Create Date: 2026-03-06 18:20:53.485313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2098aad53180'
down_revision: Union[str, Sequence[str], None] = 'd74cc7071334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('delivery_status', sa.String(), server_default='pending', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'delivery_status')
    # ### end Alembic commands ###
