"""added availability_statuses table

Revision ID: 28039c595dd1
Revises: 1c38e17ccaa9
Create Date: 2026-06-01 17:49:49.610026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28039c595dd1'
down_revision: Union[str, Sequence[str], None] = '1c38e17ccaa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availability_statuses',
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], name=op.f('availability_statuses_operator_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('availability_statuses_pkey')),
    sa.UniqueConstraint('operator_id', name=op.f('availability_statuses_operator_id_key'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('availability_statuses')
    # ### end Alembic commands ###
