"""added assigments table

Revision ID: e81e8ccace90
Revises: 2098aad53180
Create Date: 2026-03-09 11:36:30.117958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e81e8ccace90'
down_revision: Union[str, Sequence[str], None] = '2098aad53180'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assigments',
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('assigments_conversation_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], name=op.f('assigments_operator_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('assigments_pkey')),
    sa.UniqueConstraint('operator_id', 'conversation_id', name='operator_conversation_idx')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assigments')
    # ### end Alembic commands ###
